version: '3.8'

services:
  postgres-primary:
    image: postgres:16
    container_name: postgres-primary
    restart: always
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "5432:5432"
    volumes:
      - ./primary/init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - pgnet

  postgres-replica1:
    image: postgres:16
    container_name: postgres-replica1
    restart: always
    depends_on:
      - postgres-primary
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - "5433:5432"
    command: >
      bash -c "
        until pg_isready -h postgres-primary -p 5432; do sleep 1; done &&
        pg_basebackup -h postgres-primary -D /var/lib/postgresql/data -U ${POSTGRES_USER} -Fp -Xs -P -R &&
        echo \"primary_conninfo = 'host=postgres-primary port=5432 user=${POSTGRES_USER} password=${POSTGRES_PASSWORD}'\" >> /var/lib/postgresql/data/postgresql.auto.conf &&
        postgres
      "
    networks:
      - pgnet

  postgres-replica2:
    image: postgres:16
    container_name: postgres-replica2
    restart: always
    depends_on:
      - postgres-primary
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - "5434:5432"
    command: >
      bash -c "
        until pg_isready -h postgres-primary -p 5432; do sleep 1; done &&
        pg_basebackup -h postgres-primary -D /var/lib/postgresql/data -U ${POSTGRES_USER} -Fp -Xs -P -R &&
        echo \"primary_conninfo = 'host=postgres-primary port=5432 user=${POSTGRES_USER} password=${POSTGRES_PASSWORD}'\" >> /var/lib/postgresql/data/postgresql.auto.conf &&
        postgres
      "
    networks:
      - pgnet

networks:
  pgnet:
    driver: bridge
