version: '3.8'

services:
  postgres-primary:
    image: postgres:16
    container_name: postgres-primary
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    volumes:
      - ./primary/init.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - "5432:5432"
    networks:
      - pg-net

  postgres-replica1:
    image: postgres:16
    container_name: postgres-replica1
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_REPLICATION_ROLE: replica
    depends_on:
      - postgres-primary
    volumes:
      - ./replica:/docker-entrypoint-initdb.d
    command: >
      bash -c "
        until pg_isready -h postgres-primary; do sleep 1; done &&
        pg_basebackup -h postgres-primary -D /var/lib/postgresql/data -U postgres -Fp -Xs -P -R &&
        echo \"host replication all all trust\" >> /var/lib/postgresql/data/pg_hba.conf &&
        echo \"primary_conninfo = 'host=postgres-primary user=postgres'\" >> /var/lib/postgresql/data/postgresql.conf &&
        postgres
      "
    ports:
      - "5433:5432"
    networks:
      - pg-net

  postgres-replica2:
    image: postgres:16
    container_name: postgres-replica2
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_REPLICATION_ROLE: replica
    depends_on:
      - postgres-primary
    volumes:
      - ./replica:/docker-entrypoint-initdb.d
    command: >
      bash -c "
        until pg_isready -h postgres-primary; do sleep 1; done &&
        pg_basebackup -h postgres-primary -D /var/lib/postgresql/data -U postgres -Fp -Xs -P -R &&
        echo \"host replication all all trust\" >> /var/lib/postgresql/data/pg_hba.conf &&
        echo \"primary_conninfo = 'host=postgres-primary user=postgres'\" >> /var/lib/postgresql/data/postgresql.conf &&
        postgres
      "
    ports:
      - "5434:5432"
    networks:
      - pg-net

networks:
  pg-net:
    driver: bridge
